# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x0estock.protobuf\"\xa5\x04\n\x11StockPriceMessage\x12\r\n\x05price\x18\x01 \x01(\x05\x12\x0c\n\x04\x62id1\x18\x02 \x01(\x05\x12\x0e\n\x06offer1\x18\x03 \x01(\x05\x12\x0c\n\x04\x62id2\x18\x04 \x01(\x05\x12\x0e\n\x06offer2\x18\x05 \x01(\x05\x12\x0c\n\x04\x62id3\x18\x06 \x01(\x05\x12\x0e\n\x06offer3\x18\x07 \x01(\x05\x12\x0f\n\x07\x62id1Vol\x18\x08 \x01(\x03\x12\x11\n\toffer1Vol\x18\t \x01(\x03\x12\x0f\n\x07\x62id2Vol\x18\n \x01(\x03\x12\x11\n\toffer2Vol\x18\x0b \x01(\x03\x12\x0f\n\x07\x62id3Vol\x18\x0c \x01(\x03\x12\x11\n\toffer3Vol\x18\r \x01(\x03\x12\x15\n\rchangePercent\x18\x0e \x01(\x02\x12\x0e\n\x06symbol\x18\x0f \x01(\t\x12\x0e\n\x06\x63hange\x18\x10 \x01(\x05\x12\x0b\n\x03vol\x18\x11 \x01(\x03\x12\x11\n\tremainBid\x18\x12 \x01(\x03\x12\x11\n\tremainAsk\x18\x13 \x01(\x03\x12\x15\n\rforeignBought\x18\x14 \x01(\x03\x12\x13\n\x0b\x66oreignSold\x18\x15 \x01(\x03\x12\x15\n\rforeignRemain\x18\x16 \x01(\x03\x12\x10\n\x08totalVol\x18\x17 \x01(\x03\x12\x10\n\x08totalVal\x18\x18 \x01(\x03\x12\x0c\n\x04high\x18\x19 \x01(\x05\x12\x0e\n\x06medium\x18\x1a \x01(\x05\x12\x0b\n\x03low\x18\x1b \x01(\x05\x12\x0f\n\x07\x63\x65iling\x18\x1c \x01(\x05\x12\x11\n\treference\x18\x1d \x01(\x05\x12\r\n\x05\x66loor\x18\x1e \x01(\x05\x12\x0c\n\x04name\x18\x1f \x01(\t\"O\n\x15StockPriceMessageList\x12\x36\n\x0bstockPrices\x18\x01 \x03(\x0b\x32!.stock.protobuf.StockPriceMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOCKPRICEMESSAGE._serialized_start=32
  _STOCKPRICEMESSAGE._serialized_end=581
  _STOCKPRICEMESSAGELIST._serialized_start=583
  _STOCKPRICEMESSAGELIST._serialized_end=662
# @@protoc_insertion_point(module_scope)
